services:
  app:
    build: .
    container_name: prismaapi-app
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - ./src:/home/node/app/src:ro  
      - ./prisma:/home/node/app/prisma:ro
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydatabase?schema=public
    user: "node"
    command: sh -c "sleep 10 && npx prisma db push && npm run start:dev"

  db:
    build: .docker/postgres
    container_name: prismaapi-db
    restart: always
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase

volumes:
  postgres_data:
